/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseDrawer: typeof import('./src/components/BaseDrawer.vue')['default']
    DrawingPanel: typeof import('./src/components/Map/DrawingPanel.vue')['default']
    EditUserDrawer: typeof import('./src/components/users/EditUserDrawer.vue')['default']
    FarmDeleteDialog: typeof import('./src/components/Farms/FarmDeleteDialog.vue')['default']
    FarmForm: typeof import('./src/components/Farms/FarmForm.vue')['default']
    FarmList: typeof import('./src/components/Farms/FarmList.vue')['default']
    FarmsMenu: typeof import('./src/components/Map/FarmsMenu.vue')['default']
    FarmTableActions: typeof import('./src/components/Farms/FarmTableActions.vue')['default']
    FarmUploadTiff: typeof import('./src/components/Farms/FarmUploadTiff.vue')['default']
    FarmViewDialog: typeof import('./src/components/Farms/FarmViewDialog.vue')['default']
    GeoJSONLayer: typeof import('./src/components/Map/GeoJSONLayer.vue')['default']
    GeoJsonProcessor: typeof import('./src/components/Farms/GeoJsonProcessor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MapControls: typeof import('./src/components/Map/MapControls.vue')['default']
    RegisterUserDrawer: typeof import('./src/components/users/RegisterUserDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    StatusActions: typeof import('./src/components/Map/StatusActions.vue')['default']
    StepperFooter: typeof import('./src/components/Farms/StepperFooter.vue')['default']
    TiffProcessor: typeof import('./src/components/Map/TiffProcessor.vue')['default']
    UserDeleteDialog: typeof import('./src/components/Users/UserDeleteDialog.vue')['default']
    UserForm: typeof import('./src/components/Users/UserForm.vue')['default']
    UserList: typeof import('./src/components/Users/UserList.vue')['default']
    UserTableActions: typeof import('./src/components/Users/UserTableActions.vue')['default']
    WeedsOverlay: typeof import('./src/components/Map/WeedsOverlay.vue')['default']
  }
}