/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseDrawer: typeof import('./src/components/BaseDrawer.vue')['default']
    EditUserDrawer: typeof import('./src/components/users/EditUserDrawer.vue')['default']
    FarmDeleteDialog: typeof import('./src/components/Farms/FarmDeleteDialog.vue')['default']
    FarmForm: typeof import('./src/components/Farms/FarmForm.vue')['default']
    FarmList: typeof import('./src/components/Farms/FarmList.vue')['default']
    FarmTableActions: typeof import('./src/components/Farms/FarmTableActions.vue')['default']
    GeoJsonProcessor: typeof import('./src/components/Farms/GeoJsonProcessor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RegisterUserDrawer: typeof import('./src/components/users/RegisterUserDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
